name: Build and Deploy GH Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REACT_APP_SPOONACULAR_API_KEY: ${{ secrets.REACT_APP_SPOONACULAR_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          
      - name: Install
        run: npm install

      - name: Build and Deploy
        run: |
          npm run deploy
